app = "kalaclista-reader"
primary_region = "nrt"
swap_size_mb = 256

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
    [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 400

[[mounts]]
destination = "/data"
source = "kalaclista_reader_data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
